dist: xenial

git:
  depth: 5

matrix:
  include:
    - env:
        - task=shellcheck
      language: node_js
      node_js:
        - "8"
      cache:
        directories:
          - .npx
      script:
        - npx --cache .npx dockerfile_lint
